---
title: "Probability Theory"
---

# Assignment 1
```{r}
P_S<-0.3
P_notS<-0.7

P_T_after_S<-0.2
P_notT_after_S<-0.8
P_T_after_notS<-0.6
P_notT_after_notS<-0.4

P_T_and_S<-P_T_after_S*P_S
P_notT_and_S<-P_notT_after_S*P_S
P_T_and_notS<-P_T_after_notS*P_notS
P_notT_and_notS<-P_notT_after_notS*P_notS

sprintf("P(T and S) = %.3f; P(T and notS) = %.3f; P(notT and S) = %.3f; P(notT and notS) = %.3f; Sum = %.3f", P_T_and_S, P_T_and_notS, P_notT_and_S, P_notT_and_notS, P_T_and_S+P_T_and_notS+P_notT_and_S+P_notT_and_notS)
```


# Assignment 2
```{r}
P_S_notT_notC<-0.423
P_T_notS_notC<-0.278
P_C_notT_notS<-0.1

P_SandT_notSandTandC<-0.073
P_TandC_notSandTandC<-0.033
P_SandC_notSandTandC<-0.088

P_SandTandC<-0.005
```
## Percentage of customers using ALL three devices
```{r}
P_allDevices<-P_SandTandC
sprintf("Percentage of customers using all three devices: %.3f",P_allDevices)
```
## Percentage of customers using AT LEAST two devices
```{r}
P_atLeastTwoDevices<-P_SandT_notSandTandC+P_TandC_notSandTandC+P_SandC_notSandTandC+P_SandTandC
sprintf("Percentage of customers using at least two devices: %.3f", P_atLeastTwoDevices)
```
## Percentage of customers using ONLY one device
```{r}
P_onlyOneDevice<-P_S_notT_notC+P_T_notS_notC+P_C_notT_notS
sprintf("Percentage of customers using only one device: %.3f", P_onlyOneDevice)
```
## Check total probability (has to be 1)
```{r}
P_total<-P_atLeastTwoDevices+P_onlyOneDevice
sprintf("Total probability: %.3f", P_total)
```


# Assignment 3
```{r}
P_B_after_A<-0.97
P_B_after_notA<-0.01
P_A<-0.04

P_notA<-1-P_A

P_notA_after_B<-(P_B_after_notA*P_notA/(P_B_after_notA*P_notA+P_B_after_A*P_A))
sprintf("P(notA|B) = %.3f", P_notA_after_B)

P_A_after_B<-(P_B_after_A*P_A/(P_B_after_A*P_A+P_B_after_notA*P_notA))
sprintf("P(A|B) = %.3f", P_A_after_B)

Answer_vect<-c("These results show that in case the alarm is triggered, there is a possibility of about ", round(P_notA_after_B*100,digits=1), "% that the product is flawless and a probability of ", round(P_A_after_B*100,digits=1), "% that the product is faulty.")
Answer<-paste(Answer_vect,collapse="")
Answer
```